/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package action.news;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.management.BoNavigation;
import model.management.BoSpecial;
import model.news.BoNews;
import model.system.PageList;

import org.apache.commons.fileupload.FileItem;
import org.apache.commons.fileupload.disk.DiskFileItemFactory;
import org.apache.commons.fileupload.servlet.ServletFileUpload;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;

import service.facility.BoFacilityTypeService;
import service.management.BoNavigationService;
import service.management.BoSpecialService;
import service.news.BoNewsService;
import factory.ServiceFactory;

/** 
 * MyEclipse Struts
 * Creation date: 02-15-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class NewsManageActionAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		if (request.getParameter("action").equals("toManagePage")) {
			DynaActionForm pageListForm = (DynaActionForm) form;
			BoNewsService s = (BoNewsService) ServiceFactory.instance()
					.getService("boNewsService");
			PageList pageList = new PageList();
			if (pageListForm.get("fetch") != null) {
				pageList.setFetch(Integer.parseInt(pageListForm.get("fetch")
						.toString()));
			}
			if (pageListForm.get("pagenum") != null) {
				pageList.setPagenum(Integer.parseInt(pageListForm
						.get("pagenum").toString()));
			}
			if (pageListForm.get("q1") != null) {
				pageList.setQ1(pageListForm.get("q1").toString());
				//System.out.println("q1============"+pageListForm.get("q1").toString());
			} 
			if (pageListForm.get("q2") != null) {
				pageList.setQ2(pageListForm.get("q2").toString());
				//System.out.println("q2============"+pageListForm.get("q2").toString());

			}
			if (pageListForm.get("q3") != null) {
				pageList.setQ3(pageListForm.get("q3").toString());
				//System.out.println("q3============"+pageListForm.get("q3").toString());

			}
			if (pageListForm.get("q4") != null) {
				pageList.setQ4(pageListForm.get("q4").toString());
				//System.out.println("q4============"+pageListForm.get("q4").toString());

			}
			if (pageListForm.get("q5") != null) {
				pageList.setQ5(pageListForm.get("q5").toString());
				//System.out.println("q5============"+pageListForm.get("q5").toString());

			}
			if (pageListForm.get("q6") != null) {
				pageList.setQ6(pageListForm.get("q6").toString());
				//System.out.println("q6============"+pageListForm.get("q6").toString());

			}
			if (pageListForm.get("q7") != null) {
				pageList.setQ7(pageListForm.get("q7").toString());
				//System.out.println("q7============"+pageListForm.get("q7").toString());

			}
			if (pageListForm.get("q8") != null) {
				pageList.setQ8(pageListForm.get("q8").toString());
				//System.out.println("q8============"+pageListForm.get("q8").toString());

			}
			if (pageListForm.get("q9") != null) {
				pageList.setQ9(pageListForm.get("q9").toString());
				//System.out.println("q9============"+pageListForm.get("q9").toString());

			}
			if (pageListForm.get("q10") != null) {
				pageList.setQ10(pageListForm.get("q10").toString());
				//System.out.println("q9============"+pageListForm.get("q9").toString());
			}
			
			
			
			
			Map map = s.getBoNewsMap(pageList);
			pageList = (PageList) map.get("pageList");
			List list = (List) map.get("list");

			request.setAttribute("pageList", pageList);
			request.setAttribute("list", list);

			BoNavigationService boNavigationService = (BoNavigationService) ServiceFactory
					.instance().getService("boNavigationService");
			BoSpecialService boSpecialService = (BoSpecialService) ServiceFactory
			.instance().getService("boSpecialService");
			List secondList = boNavigationService.getSecondNodeList();
			List firstList = boNavigationService.getBoNavigationRootList();
			
			
			List secondList2 = boSpecialService.getSmallBoSpecial();
			List firstList2 = boSpecialService.getAllBoSpecial();

			request.setAttribute("secondList", secondList);
			request.setAttribute("firstList", firstList);

			request.setAttribute("secondList2", secondList2);
			request.setAttribute("firstList2", firstList2);

			List slist = boSpecialService.getAllBoSpecial();
			request.setAttribute("slist", slist);
			
			

			return mapping.findForward("toManagePage");
		}
		if (request.getParameter("action").equals("toCheckPage")) {
			DynaActionForm pageListForm = (DynaActionForm) form;
			BoNewsService s = (BoNewsService) ServiceFactory.instance()
					.getService("boNewsService");
			PageList pageList = new PageList();
			if (pageListForm.get("fetch") != null) {
				pageList.setFetch(Integer.parseInt(pageListForm.get("fetch")
						.toString()));
			}
			if (pageListForm.get("pagenum") != null) {
				pageList.setPagenum(Integer.parseInt(pageListForm
						.get("pagenum").toString()));
			}
			if (pageListForm.get("q1") != null) {
				pageList.setQ1(pageListForm.get("q1").toString());
				//System.out.println("q1============"+pageListForm.get("q1").toString());
			} 
			if (pageListForm.get("q2") != null) {
				pageList.setQ2(pageListForm.get("q2").toString());
				//System.out.println("q2============"+pageListForm.get("q2").toString());

			}
			if (pageListForm.get("q3") != null) {
				pageList.setQ3(pageListForm.get("q3").toString());
				//System.out.println("q3============"+pageListForm.get("q3").toString());

			}
			if (pageListForm.get("q4") != null) {
				pageList.setQ4(pageListForm.get("q4").toString());
				//System.out.println("q4============"+pageListForm.get("q4").toString());

			}
			if (pageListForm.get("q5") != null) {
				pageList.setQ5(pageListForm.get("q5").toString());
				//System.out.println("q5============"+pageListForm.get("q5").toString());

			}
			if (pageListForm.get("q6") != null) {
				pageList.setQ6(pageListForm.get("q6").toString());
				//System.out.println("q6============"+pageListForm.get("q6").toString());

			}
			if (pageListForm.get("q7") != null) {
				pageList.setQ7(pageListForm.get("q7").toString());
				//System.out.println("q7============"+pageListForm.get("q7").toString());

			}
			if (pageListForm.get("q8") != null) {
				pageList.setQ8(pageListForm.get("q8").toString());
				//System.out.println("q8============"+pageListForm.get("q8").toString());

			}
			if (pageListForm.get("q9") != null) {
				pageList.setQ9(pageListForm.get("q9").toString());
				//System.out.println("q9============"+pageListForm.get("q9").toString());

			}
			if (pageListForm.get("q10") != null) {
				pageList.setQ10(pageListForm.get("q10").toString());
				//System.out.println("q9============"+pageListForm.get("q9").toString());
			}
			Map map = s.getBoNewsMap(pageList);
			pageList = (PageList) map.get("pageList");
			List list = (List) map.get("list");

			request.setAttribute("pageList", pageList);
			request.setAttribute("list", list);

			BoNavigationService boNavigationService = (BoNavigationService) ServiceFactory
					.instance().getService("boNavigationService");
			List secondList = boNavigationService.getSecondNodeList();
			List firstList = boNavigationService.getBoNavigationRootList();
			BoSpecialService boSpecialService = (BoSpecialService) ServiceFactory
			.instance().getService("boSpecialService");
			request.setAttribute("secondList", secondList);
			request.setAttribute("firstList", firstList);
			
			List secondList2 = boSpecialService.getSmallBoSpecial();
			List firstList2 = boSpecialService.getAllBoSpecial();


			request.setAttribute("secondList2", secondList2);
			request.setAttribute("firstList2", firstList2);

			List slist = boSpecialService.getAllBoSpecial();
			request.setAttribute("slist", slist);
			return mapping.findForward("toCheckPage");
		}
		if (request.getParameter("action").equals("toViewPage")) {

			BoNavigationService boNavigationService = (BoNavigationService) ServiceFactory
					.instance().getService("boNavigationService");
			List rootList = boNavigationService.getNodeManage();
			List mainList = boNavigationService.getBoNavigationRootList();

			request.setAttribute("rootList", rootList); //获取所有大小类
			request.setAttribute("mainList", mainList); //获取大类字段
			request.setAttribute("trLSize", rootList.size());
			BoNavigation checked = boNavigationService.getCheckedBoNavigation();
			request.setAttribute("checked", checked);
			BoNewsService s = (BoNewsService) ServiceFactory.instance()
					.getService("boNewsService");
			BoNews b = s.getBoNews(request.getParameter("id"));
			String enclo = b.getNewsEnclo();
			//System.out.println(enclo + "*****************");
			if (enclo != null) {
				String[] enclosure = enclo.split("/");
				request.setAttribute("enclo", enclosure);
			}
			String name = "";
			String id = "";
			////System.out.println("小类的ID是："+b.getNewsSmall());

			//  String smallid=b.getNewsSmall();
			// BoNavigation boNav =boNavigationService.getBoNavigation(smallid);

			if (b.getBoNavigationByNewsSmall() != null) //如果小类ID不为空，需要获得小类的ID和名字作为二级菜单显示
			{
				BoNavigation boNav = boNavigationService.getBoNavigation(b
						.getBoNavigationByNewsSmall().getId());

				//System.out.println("小类ID不为空！！");
				name = boNav.getName();
				id = boNav.getId();
			}

			if (b.getBoSpecial() != null) //如果专题ID不为空，需要获得专题的ID和名字作为二级菜单显示
			{
				BoSpecialService bospecial = (BoSpecialService) ServiceFactory
						.instance().getService("boSpecialService");
				name = bospecial.getBoSpecial(b.getBoSpecial().getId())
						.getName();
				id = b.getBoSpecial().getId();
			}
			BoSpecialService bospecial = (BoSpecialService) ServiceFactory
					.instance().getService("boSpecialService");
			List special = bospecial.getAllBoSpecial();
			request.setAttribute("specialsize", special.size()); //获取专题的名称
			request.setAttribute("special", special);

			request.setAttribute("smallname", name); //用于二级菜单的显示名字
			request.setAttribute("smallid", id); //用于二级菜单的id显示
			request.setAttribute("mes", b);
			return mapping.findForward("toViewPage");
		}

		if (request.getParameter("action").equals("tohavechecked")) {

			BoNewsService boNavigationService = (BoNewsService) ServiceFactory
					.instance().getService("boNewsService");
			String newsid = request.getParameter("id");
			//System.out.println("后台接收到的ID" + newsid);
			BoNews bo = boNavigationService.getBoNews(newsid);
			String check = bo.getNewsCheck();
			if (check.equals("0")) {
				bo.setNewsCheck("1");

			}

			boNavigationService.updateBoNews(bo);

			return new ActionForward("/newsManageAction.do?action=toCheckPage");
		}

		return null;
	}

}